### ISSUE TITLE
Invalid byte sequence on UTF-8

### ISSUE THREAD

**Issue by jerivl** [inukshuk/wapiti-ruby#11]
I get the following error whenever wapiti is invoked on MacOS Ventura 13.3.1 when installed with gem.
```
  invalid byte sequence in UTF-8
  /Users/jer/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/wapiti-2.1.0/lib/wapiti/dataset.rb:25:in `split'
  /Users/jer/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/wapiti-2.1.0/lib/wapiti/dataset.rb:25:in `parse'
  ...
```

**Comment by inukshuk** [comment]
What's the input you're parsing (and how)?

**Comment by jerivl** [comment]
I am trying to invoke it through one of your other projects through `anystyle parse [path_to/paper_name]`

I was a bit unsure which repo to post this issue in, but we can move this to the anystyle one if preferred.

**Comment by inukshuk** [comment]
Is that via the CLI? If so, what format is your paper in? The `anystyle parse` command takes text files as input (one reference per line). If this is a full PDF paper you need to extract the references first, for example using the `anystyle find` module.

**Comment by jerivl** [comment]
Ah thank you. That was my problem.
